# Generated by Django 4.0 on 2022-08-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Specialization',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.IntegerField(),
        ),
    ]
