# Generated by Django 4.0 on 2022-08-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
