# Generated by Django 4.0 on 2022-08-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_comment_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='doctor',
            new_name='profile',
        ),
    ]
