# Generated by Django 4.0 on 2022-08-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_delete_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.CharField(blank=True, choices=[('recommend', 'recommend'), ('neutral', 'neutral'), ('not recommend', 'not recommend')], max_length=50, null=True),
        ),
    ]
